spring:
  application:
    name: ms-hr-employees
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: hr
    password: hrpw
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  servlet:
    context-path: /ms-hr-employees/v1
  port: 9091

api:
  support:
    ms-human-resources-areas:
      url: http://localhost:9092/ms-hr-areas/v1
  areas-service:
    name: ms-hr-areas

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
