spring:
  application:
    name: ms-hr-employees
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: hr
    password: hrpw
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 9091

api:
  support:
    ms-human-resources-areas:
      url: http://localhost:9092/ms-hr-areas/v1
  areas-service:
    name: ms-hr-areas

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
    ratelimiters:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    metrics:
      enabled: true

resilience4j.circuitbreaker:
  configs:
    default:
      registerHealthIndicator: true

resilience4j.ratelimiter:
  configs:
    default:
      registerHealthIndicator: true
