spring:
  application:
    name: ms-hr-areas
  datasource:
    url: jdbc:oracle:thin:@//localhost:1521/XE
    username: hr
    password: hrpw
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    show-sql: true
    properties:
      hibernate.format_sql: true

server:
  servlet:
    context-path: /ms-hr-areas/v1
  port: 9092
