spring:
  application:
    name: ms-hr-discovery-server
  config:
    import: optional:configserver:${SPRING_CONFIG_SERVER_URI:http://localhost:8888/}

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

info:
  environment: local