server:
  port: 8080

spring:
  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CONFIG_SERVER_GIT_URI}
          defaultLabel: ${SPRING_CONFIG_SERVER_GIT_BRANCH}
          searchPaths: 
            - config
