server:
  port: 8888

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/kuroshan/workshop-ms
          defaultLabel: 16-container
          searchPaths: 
            - config
