server:
  port: 8080

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    serviceUrl:
      defaultZone: ${SPRING_DISCOVERY_SERVER_URI}

zuul:
  ignoredServices: '*'
  prefix: /api
  routes:
    ms-human-resources-users:
      service-id: MS-HR-USERS
      path: /hr/authorization/**
      strip-prefix: true
    ms-human-resources-areas:
      service-id: MS-HR-AREAS
      path: /hr/areas/**
      strip-prefix: true
    ms-human-resources-employees:
      service-id: MS-HR-EMPLOYEES
      path: /hr/payroll/**
      strip-prefix: true
    ms-human-resources-security:
      service-id: MS-HR-SECURITY-SERVICE
      path: /hr/authentication/**
      strip-prefix: true
      sensitive-headers:
        - Cookie
        - Set-Cookie

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000

management:
  endpoints:
    web:
      exposure:
        include: '*'

security:
  oauth:
    jwt:
      key: token_secrect_key

info:
  environment: predeterminado