spring:
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_DISCOVERY_SERVER_URI}

security:
  oauth:
    client:
      secrect: basic_secrect_dev_key
    jwt:
      key: token_secrect_dev_key

info:
  environment: desarrollo