server:
  port: 9083

spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8002/eureka/

info:
  environment: desarrollo