spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_DISCOVERY_SERVER_URI}

info:
  environment: desarrollo