server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: ${SPRING_DISCOVERY_SERVER_URI}

security:
  oauth:
    jwt:
      key: token_secrect_dev_key

info:
  environment: desarrollo