spring:
  jpa:
    show-sql: false
    properties:
      hibernate.format_sql: false

server:
  port: 9091

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

info:
  environment: desarrollo