version: '3.7'
services:
  database-mysql:
    image: database-mysql:v1
    container_name: database-mysql-dev
    ports: 
      - "3306:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: securitydb
      MYSQL_USER: admin
      MYSQL_PASSWORD: mysql
    networks: 
      - workshopms
  database-redis:
    image: database-redis:v1
    container_name: database-redis-dev
    ports: 
      - "6379:6379"
    restart: always
    networks: 
      - workshopms
  database-oracle:
    image: database-oracle:v1
    container_name: database-oracle-dev
    ports: 
      - "1521:1521"
    restart: always
    networks: 
      - workshopms      
networks: 
  workshopms:
    name: workshopms-net-dev